%YAML 1.2
---
name: 'ehs1_l'

dataset:
  num_chunks: 100
  train_ratio: 0.90
  input: '/tmp/ehs-data2/'

training:
  batch_size: 512
  test_steps: 2000
  train_avg_report_steps: 150
  total_steps: 14000
  warmup_steps: 250
  lr_values:
    - 0.1
    - 0.02
    - 0.002
    - 0.0005
  lr_boundaries:
    - 8000
    - 10000
    - 13000
  value_loss_weight: 1.0
  path: '/tmp/networks/'

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 2
