%YAML 1.2
---
name: 'hu1'

dataset:
  num_chunks: 100
  train_ratio: 0.90
  input: '/tmp/train-1/'

training:
  batch_size: 2048
  test_steps: 20
  total_steps: 30
  warmup_steps: 20
  lr_values:
    - 0.02
    - 0.002
    - 0.0005
  lr_boundaries:
    - 100000
    - 130000
  rank_loss_weight: 1.0
  card_loss_weight: 1.0
  path: '/tmp/networks/'

model:
  filters: 64
  residual_blocks: 6
