%YAML 1.2
---
name: 'ehs1_river_3x64'

dataset:
  num_chunks: 100
  train_ratio: 0.90
  input: '/tmp/ehs-data/river/'

training:
  batch_size: 4
  test_steps: 2000
  train_avg_report_steps: 150
  total_steps: 28000
  warmup_steps: 250
  lr_values:
    - 0.00002
    - 0.000002
    - 0.0000002
  lr_boundaries:
    - 19000
    - 26000
  value_loss_weight: 1.0
  path: '/tmp/networks/'

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 2
