%YAML 1.2
---
name: 'ehs1_mix_0x16_relu'

dataset:
  num_chunks: 3024
  train_ratio: 0.90
  input: '/tmp/ehs-data/data_mix/data/'

training:
  batch_size: 2048
  test_steps: 2000
  train_avg_report_steps: 150
  total_steps: 36000
  warmup_steps: 250
  shuffle_size: 524288
  lr_values:
    - 0.02
    - 0.002
    - 0.0003
    - 0.00003
  lr_boundaries:
    - 10000
    - 22000
    - 34000
  value_loss_weight: 1.0
  path: '/tmp/networks/'

model:
  filters: 16
  residual_blocks: 0
  se_ratio: 2
