%YAML 1.2
---
name: 'ehs1_turn_3x32'

dataset:
  num_chunks: 224
  train_ratio: 0.90
  input: '../lheadsup-play/backup_data/turn/data-06_09_0225/'

training:
  batch_size: 1024
  test_steps: 2000
  train_avg_report_steps: 150
  total_steps: 36000
  warmup_steps: 250
  shuffle_size: 224288
  lr_values:
    - 0.00006
    - 0.00001
    - 0.000002
  lr_boundaries:
    - 10000
    - 40000
  value_loss_weight: 1.0
  path: '/tmp/networks/'

model:
  filters: 32
  residual_blocks: 3
  se_ratio: 2
