%YAML 1.2
---
name: 'ehs1_flop_3x32'

dataset:
  num_chunks: 1120
  train_ratio: 0.90
  input: '/tmp/ehs-data/data_1120_flop/'

training:
  batch_size: 512
  test_steps: 2000
  train_avg_report_steps: 150
  total_steps: 36000
  warmup_steps: 250
  shuffle_size: 124288
  lr_values:
    - 0.00002
    - 0.000002
    - 0.0000003
  lr_boundaries:
    - 28000
    - 32000
  value_loss_weight: 1.0
  path: '/tmp/networks/'

model:
  filters: 32
  residual_blocks: 3
  se_ratio: 2
