%YAML 1.2
---
name: 'ehs1_river_3x32_debug'

dataset:
  num_chunks: 100
  train_ratio: 0.90
  input: '/tmp/ehs-data/river/'

training:
  batch_size: 512
  test_steps: 200
  train_avg_report_steps: 150
  total_steps: 1600
  warmup_steps: 250
  lr_values:
    - 0.00001
    - 0.000001
    - 0.000003
  lr_boundaries:
    - 28000
    - 34000
  value_loss_weight: 1.0
  path: '/tmp/networks/'

model:
  filters: 32
  residual_blocks: 3
  se_ratio: 2
