%YAML 1.2
---
name: 'ehs1_river_3x32_debug'

dataset:
  num_chunks: 1680
  train_ratio: 0.9
  input: '../lheadsup-play/data/data_all/'

training:
  batch_size: 1024
  test_steps: 1000
  train_avg_report_steps: 150
  total_steps: 36000
  warmup_steps: 2500
  shuffle_size: 20000
  lr_values:
    - 0.002
    - 0.0002
    - 0.00003
  lr_boundaries:
    - 28000
    - 34000
  value_loss_weight: 1.0
  path: '/tmp/networks/'

model:
  filters: 32
  residual_blocks: 0
  se_ratio: 2
