%YAML 1.2
---
name: 'ehs1_river_2x256'

dataset:
  num_chunks: 1680
  train_ratio: 0.90
  input: '/tmp/ehs-data/data_all/'

training:
  batch_size: 2048
  test_steps: 2000
  train_avg_report_steps: 150
  total_steps: 36000
  warmup_steps: 250
  shuffle_size: 524288
  lr_values:
    - 0.02
    - 0.002
    - 0.0002
  lr_boundaries:
    - 10000
    - 32000
  value_loss_weight: 1.0
  path: '/tmp/networks/'

model:
  filters: 256
  residual_blocks: 2
  se_ratio: 2
