%YAML 1.2
---
name: 'ehs2_mix_3x32'

dataset:
  num_chunks: 64
  train_ratio: 0.90
  input: '/tmp/ehs-data/data_v2/all/'

training:
  batch_size: 64
  test_steps: 2000
  train_avg_report_steps: 150
  total_steps: 36000
  warmup_steps: 250
  shuffle_size: 24288
  lr_values:
    - 0.02
    - 0.002
    - 0.0003
    - 0.00003
  lr_boundaries:
    - 18000
    - 28000
    - 34000
  value_loss_weight: 1.0
  path: '/tmp/networks/'

model:
  filters: 32
  residual_blocks: 3
  se_ratio: 2
